import type { Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "opp-product-engineer",
    scene: "startup",
    channel: "founder",
    type: "两周试合作",
    title: "把 AI 日程助手做出第一版",
    summary: "一位做过效率产品的产品经理，想找工程搭档完成可测试的 Web 原型。",
    description:
      "不急着谈长期合伙，先用两周做出一个可以交给 10 位用户试用的版本。方向已经过访谈验证，当前最缺能快速搭起前后端闭环的人。",
    tags: ["AI 产品", "远程", "试合作"],
    members: 1,
    minMembers: 2,
    maxMembers: 3,
    startsAt: "2026-07-20T19:30:00+08:00",
    endsAt: "2026-07-20T21:30:00+08:00",
    registrationDeadline: "2026-07-20T16:00:00+08:00",
    cancellationDeadline: "2026-07-20T12:00:00+08:00",
    city: "上海",
    venue: "愚园路共创空间",
    address: "上海市长宁区愚园路 1088 号 3F",
    distanceKm: 3.2,
    price: { type: "free", note: "场地由发起人承担" },
    organizer: { name: "林岸", role: "产品发起人", verified: true },
    registrationMode: "approval",
    agenda: ["19:30 彼此介绍正在验证的问题", "20:00 对齐首轮原型边界", "20:50 确定两周协作方式"],
    notices: ["请带上正在使用的原型或流程图", "确认加入后开放临时协作群"],
    reason: "双方都希望先用小实验验证配合，而且这个局正缺能把想法变成产品的人。",
    observation: "目标清楚、时间边界明确。适合愿意先做事再谈长期关系的人。",
    people: [
      {
        name: "林岸",
        summary: "上海，做过三年效率工具产品，现在独立验证 AI 日程方向。",
        offer: "用户访谈、产品定义与首批测试用户",
      },
    ],
  },
  {
    id: "opp-growth-partner",
    scene: "startup",
    channel: "founder",
    type: "早期合伙",
    title: "寻找懂内容增长的长期搭档",
    summary: "小型创作者工具已有付费用户，寻找能从零搭建内容与增长体系的伙伴。",
    description:
      "产品已稳定运行半年，有 30 多位付费用户。发起人偏技术，希望找到能直接面对用户、建立内容渠道和增长节奏的长期搭档。",
    tags: ["内容增长", "创作者", "上海"],
    members: 2,
    minMembers: 2,
    maxMembers: 4,
    startsAt: "2026-07-21T19:00:00+08:00",
    endsAt: "2026-07-21T21:00:00+08:00",
    registrationDeadline: "2026-07-21T15:00:00+08:00",
    cancellationDeadline: "2026-07-21T12:00:00+08:00",
    city: "上海",
    venue: "静安创业会客厅",
    address: "上海市静安区陕西北路 600 号",
    distanceKm: 5.6,
    price: { type: "aa", note: "饮品到店自付，预计 35–60 元" },
    organizer: { name: "周屿", role: "独立开发者", verified: true },
    registrationMode: "approval",
    agenda: ["19:00 业务与用户现状", "19:35 增长案例拆解", "20:20 小范围协作意向"],
    notices: ["请准备一个最能代表你方法的增长案例", "不现场承诺长期合作"],
    reason: "你关注真实用户价值，而这个团队需要的不只是投放经验，更是能一起定义增长方向的人。",
    observation: "已经成局，仍开放一位核心伙伴。建议先确认对全职时间表的期待。",
    people: [
      { name: "周屿", summary: "全栈工程师，连续创业者。", offer: "产品、技术和现有收入" },
      { name: "嘉禾", summary: "独立设计师，负责体验与品牌。", offer: "设计系统和创作者社群" },
    ],
  },
  {
    id: "opp-capital-seed-round",
    scene: "startup",
    channel: "capital",
    type: "种子轮交流",
    title: "工业质检产品，寻找懂制造业的种子轮伙伴",
    summary: "团队已完成两家工厂试点，准备为产品化和销售验证寻找下一阶段资金。",
    description:
      "产品用视觉模型辅助工厂完成外观质检，已有两家付费试点。团队希望认识了解制造业数字化、愿意先看真实使用数据的早期投资方。",
    tags: ["融资", "工业 AI", "种子轮"],
    members: 1,
    minMembers: 2,
    maxMembers: 3,
    startsAt: "2026-07-23T19:30:00+08:00",
    endsAt: "2026-07-23T21:00:00+08:00",
    registrationDeadline: "2026-07-23T15:00:00+08:00",
    cancellationDeadline: "2026-07-22T20:00:00+08:00",
    city: "上海",
    venue: "静安创投会客厅",
    address: "确认双方意愿后发送具体地点",
    distanceKm: 4.7,
    price: { type: "free", note: "本次交流不收取费用" },
    organizer: { name: "沈拓", role: "项目负责人", verified: true },
    registrationMode: "approval",
    agenda: ["19:30 项目与试点进展", "20:00 核心数据与融资计划", "20:40 确认是否继续交换材料"],
    notices: ["请勿在未征得同意时转发材料", "本次交流不构成投资建议或融资承诺"],
    reason: "项目已有可核验试点，融资用途也较清楚，适合关注工业软件和早期产品验证的投资方先聊。",
    observation: "仍需进一步确认客户续费意愿、销售周期和本轮资金使用计划。",
    people: [
      {
        name: "沈拓",
        role: "创始人",
        summary: "连续在制造业软件领域工作八年，目前负责产品和重点客户。",
        offer: "两家真实工厂试点、完整产品原型和一线行业经验",
        need: "理解工业场景、愿意支持种子期验证的投资伙伴",
      },
    ],
  },
  {
    id: "opp-capital-project-scout",
    scene: "startup",
    channel: "capital",
    type: "项目交流",
    title: "寻找完成首轮验证的消费科技项目",
    summary: "一支关注消费科技的早期团队，希望认识已有产品和真实用户反馈的创业项目。",
    description:
      "投资团队关注软硬件结合、个人效率与新型消费服务，优先了解已经完成最小产品验证、能清楚说明用户价值和下一阶段计划的团队。",
    tags: ["投资", "消费科技", "早期项目"],
    members: 2,
    minMembers: 2,
    maxMembers: 4,
    startsAt: "2026-07-28T18:30:00+08:00",
    endsAt: "2026-07-28T20:30:00+08:00",
    registrationDeadline: "2026-07-28T12:00:00+08:00",
    cancellationDeadline: "2026-07-27T20:00:00+08:00",
    city: "上海",
    venue: "徐汇滨江会客空间",
    address: "确认加入后开放具体地址",
    distanceKm: 6.1,
    price: { type: "free", note: "场地由发起方承担" },
    organizer: { name: "程亦安", role: "早期投资人", verified: true },
    registrationMode: "approval",
    agenda: ["18:30 双方背景与方向", "19:00 产品和用户验证", "20:00 下一阶段计划与后续安排"],
    notices: ["无需准备正式路演稿，真实数据优先", "是否进入后续流程由双方分别决定"],
    reason: "投资方向、项目阶段和交流预期都表达明确，适合已完成首轮用户验证的团队进行一次低压力沟通。",
    observation: "这是投资方主动发起的项目交流，申请前应先确认行业范围和当前阶段是否匹配。",
    people: [
      {
        name: "程亦安",
        role: "投资经理",
        summary: "长期关注消费科技和个人效率产品，偏好早期、产品驱动的团队。",
        offer: "行业研究、早期资金和后续融资网络",
        need: "已经做出产品、能展示真实用户反馈的创业团队",
      },
      {
        name: "许闻舟",
        role: "产业顾问",
        summary: "负责消费品牌和硬件供应链方向的项目判断。",
        offer: "供应链、渠道和商业化建议",
        need: "产品边界清楚、愿意验证渠道效率的团队",
      },
    ],
  },
  {
    id: "opp-coffee-walk",
    scene: "love",
    channel: "play",
    type: "轻量多人局",
    title: "周日城市散步和一杯咖啡",
    summary: "四位在上海生活的朋友，想用不赶时间的方式认识新的人。",
    description:
      "从武康路附近开始，走一段不超过两小时的路线，最后找家咖啡馆坐坐。没有破冰游戏，也不要求强行活跃。",
    tags: ["上海", "散步", "轻社交"],
    members: 4,
    minMembers: 4,
    maxMembers: 6,
    startsAt: "2026-07-22T18:30:00+08:00",
    endsAt: "2026-07-22T21:00:00+08:00",
    registrationDeadline: "2026-07-22T14:00:00+08:00",
    cancellationDeadline: "2026-07-21T20:00:00+08:00",
    city: "上海",
    venue: "愚园路 1107 号门口",
    address: "上海市长宁区愚园路 1107 号",
    distanceKm: 3.8,
    price: { type: "aa", note: "步行免费，咖啡到店自付" },
    organizer: { name: "简知夏", role: "散步发起人", verified: true },
    registrationMode: "instant",
    agenda: ["18:30 集合与简单认识", "18:45 沿愚园路慢走", "20:00 找一家咖啡馆坐下"],
    notices: ["全程约 3 公里，请穿方便步行的鞋", "确认参加后可看到同行者完整介绍"],
    reason: "你希望关系从真实日常自然开始，这个局节奏轻，也给彼此留下充分观察空间。",
    observation: "成员都偏慢热，活动安排克制。当前还剩两席。",
    people: [
      { name: "简知夏", role: "编辑", summary: "常在周末逛旧书店，也熟悉这段街区。", offer: "路线与咖啡店清单", need: "认识同样愿意慢慢走路聊天的人" },
      { name: "沈牧川", role: "交互设计师", summary: "喜欢城市观察和不赶时间的周末。", offer: "轻松、不催促的相处节奏", need: "认识生活半径相近的新朋友" },
      { name: "陈雨茉", role: "纪录片策划", summary: "刚搬到上海一年，希望把城市生活过得更具体。", offer: "展览与电影活动清单", need: "稳定但不过度密集的线下朋友" },
      { name: "顾行之", role: "建筑摄影师", summary: "工作日常在街区走访，偏慢热。", offer: "城市空间观察和拍摄经验", need: "能一起散步、看展的人" },
    ],
  },
  {
    id: "opp-serious-relationship",
    scene: "love",
    channel: "love",
    type: "一对一认识",
    title: "认真认识，也允许慢一点",
    summary: "一位在杭州工作的建筑师，希望认识同样以长期关系为目标的人。",
    description:
      "更愿意从散步、看展或一起吃饭开始，不追求高频聊天。看重坦诚、稳定的生活节奏和对长期关系的共识。",
    tags: ["杭州", "长期关系", "慢节奏"],
    members: 1,
    minMembers: 2,
    maxMembers: 2,
    startsAt: "2026-07-24T19:00:00+08:00",
    endsAt: "2026-07-24T21:00:00+08:00",
    registrationDeadline: "2026-07-24T12:00:00+08:00",
    cancellationDeadline: "2026-07-23T20:00:00+08:00",
    city: "杭州",
    venue: "西湖文化广场附近",
    address: "确认双方意愿后发送具体地点",
    distanceKm: 1.9,
    price: { type: "aa", note: "各自承担饮品或晚餐费用" },
    organizer: { name: "知行", role: "参与者", verified: true },
    registrationMode: "approval",
    agenda: ["19:00 在公共空间见面", "19:15 散步或一起吃饭", "20:40 各自确认是否愿意再见"],
    notices: ["具体地点仅向双方发送", "任意一方都可以在见面前取消"],
    reason: "双方都把长期关系放在目标里，也都希望从低压力的线下见面开始。",
    observation: "目标和边界表达清楚，但仍需要确认城市与见面频率是否现实。",
    people: [
      { name: "知行", summary: "杭州，建筑师，工作日规律。", offer: "稳定投入和直接沟通" },
    ],
  },
  {
    id: "opp-weekend-makers",
    scene: "startup",
    channel: "founder",
    type: "周末共创",
    title: "周末做点真正上线的小东西",
    summary: "设计、开发和运营混合小组，每月选一个真实问题做成可用工具。",
    description: "不做路演项目，也不承诺创业。每月两个周末，从问题选择到发布完成一个小而完整的作品。",
    tags: ["北京", "周末", "共创"],
    members: 5,
    minMembers: 4,
    maxMembers: 8,
    startsAt: "2026-07-25T13:30:00+08:00",
    endsAt: "2026-07-25T18:30:00+08:00",
    registrationDeadline: "2026-07-24T20:00:00+08:00",
    cancellationDeadline: "2026-07-24T18:00:00+08:00",
    city: "北京",
    venue: "东四共享工作室",
    address: "北京市东城区东四十条 94 号",
    distanceKm: 6.4,
    price: { type: "aa", note: "场地与简餐 AA，预计 68 元/人" },
    organizer: { name: "陆闻舟", role: "共创主理人", verified: true },
    registrationMode: "instant",
    agenda: ["13:30 选题与分组", "14:10 快速定义最小版本", "16:30 内部演示", "18:00 决定是否继续"],
    notices: ["请自带电脑", "报名时简单说明你想完成的角色"],
    reason: "适合想保持主业、同时通过实际协作认识潜在伙伴的人。",
    observation: "参与方式灵活，但要求每月至少完整投入一个周末。",
    people: [
      { name: "陆闻舟", role: "产品设计师", summary: "负责议题组织和共创节奏。", offer: "问题库和共创流程", need: "能快速完成可用版本的工程伙伴" },
      { name: "周十一", role: "前端工程师", summary: "喜欢把小想法尽快做成可测试原型。", offer: "工程实现和部署", need: "清晰的问题定义和真实测试用户" },
      { name: "梁若谷", role: "独立开发者", summary: "长期关注本地生活和个人效率工具。", offer: "后端、数据和快速验证", need: "产品与交互反馈" },
      { name: "唐一诺", role: "内容运营", summary: "擅长把复杂产品讲成用户愿意尝试的故事。", offer: "内容测试和首批传播", need: "值得持续讲述的小产品" },
      { name: "许知遥", role: "用户研究", summary: "周末参与非商业项目，关注真实使用情境。", offer: "访谈设计和可用性测试", need: "能落到用户手里的原型" },
    ],
  },
  {
    id: "opp-travel-west-yunnan",
    scene: "love",
    channel: "travel",
    type: "旅行同行",
    title: "十月去滇西慢慢走一周",
    summary: "两位从上海出发的旅友，想找一两位预算和节奏相近的人一起走大理、沙溪和腾冲。",
    description: "路线以自然、人文和小镇慢行为主，不赶景点。计划出发前先在线聊清预算和分工，再在上海公共场所见一次，彼此都确认舒服后才分别预订交通与住宿。",
    tags: ["旅行", "滇西", "慢节奏"],
    members: 2,
    minMembers: 2,
    maxMembers: 4,
    startsAt: "2026-10-17T09:00:00+08:00",
    endsAt: "2026-10-24T19:00:00+08:00",
    registrationDeadline: "2026-09-20T20:00:00+08:00",
    cancellationDeadline: "2026-09-30T20:00:00+08:00",
    city: "上海",
    venue: "出发前线下见面",
    address: "双方确认后约在上海公共场所",
    distanceKm: 4.3,
    price: { type: "aa", note: "预算约 6500–8500 元，各自预订并承担费用" },
    organizer: { name: "程知遥", role: "行程发起人", verified: true },
    registrationMode: "approval",
    agenda: ["确认目的地、日期和预算", "对齐住宿交通、独处时间与责任分工", "线下见面后分别决定是否共同出发"],
    notices: ["平台不代订票、住宿或代收费用", "请勿在确认同行前交换身份证件等敏感信息", "任何一方都可以在预订前退出"],
    reason: "目的地、预算和旅行节奏都表达具体，也预留了出发前见面和各自确认的空间。",
    observation: "适合喜欢慢旅行、愿意共同准备但仍保留个人边界的人。",
    people: [
      { name: "程知遥", role: "产品设计师", summary: "上海，习惯提前做路线，喜欢自然和地方文化。", offer: "初版路线、住宿备选和公共交通研究", need: "愿意共同准备、节奏不赶的同行者" },
      { name: "宋闻溪", role: "自由摄影师", summary: "上海，有多次国内长线旅行经验，习惯早睡早起。", offer: "影像记录、轻量装备清单和途中应变经验", need: "预算透明、尊重彼此独处时间的旅友" },
    ],
  },
];
