import type { Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "opp-product-engineer",
    scene: "startup",
    type: "两周试合作",
    title: "把 AI 日程助手做出第一版",
    summary: "一位做过效率产品的产品经理，想找工程搭档完成可测试的 Web 原型。",
    description:
      "不急着谈长期合伙，先用两周做出一个可以交给 10 位用户试用的版本。方向已经过访谈验证，当前最缺能快速搭起前后端闭环的人。",
    tags: ["AI 产品", "远程", "试合作"],
    members: 1,
    minMembers: 2,
    maxMembers: 3,
    deadline: "2026.08.15",
    reason: "双方都希望先用小实验验证配合，而且这个局正缺能把想法变成产品的人。",
    observation: "目标清楚、时间边界明确。适合愿意先做事再谈长期关系的人。",
    people: [
      {
        name: "林岸",
        summary: "上海，做过三年效率工具产品，现在独立验证 AI 日程方向。",
        offer: "用户访谈、产品定义与首批测试用户",
      },
    ],
  },
  {
    id: "opp-growth-partner",
    scene: "startup",
    type: "早期合伙",
    title: "寻找懂内容增长的长期搭档",
    summary: "小型创作者工具已有付费用户，寻找能从零搭建内容与增长体系的伙伴。",
    description:
      "产品已稳定运行半年，有 30 多位付费用户。发起人偏技术，希望找到能直接面对用户、建立内容渠道和增长节奏的长期搭档。",
    tags: ["内容增长", "创作者", "上海"],
    members: 2,
    minMembers: 2,
    maxMembers: 4,
    deadline: "2026.09.01",
    reason: "你关注真实用户价值，而这个团队需要的不只是投放经验，更是能一起定义增长方向的人。",
    observation: "已经成局，仍开放一位核心伙伴。建议先确认对全职时间表的期待。",
    people: [
      { name: "周屿", summary: "全栈工程师，连续创业者。", offer: "产品、技术和现有收入" },
      { name: "嘉禾", summary: "独立设计师，负责体验与品牌。", offer: "设计系统和创作者社群" },
    ],
  },
  {
    id: "opp-coffee-walk",
    scene: "love",
    type: "轻量多人局",
    title: "周日城市散步和一杯咖啡",
    summary: "四位在上海生活的朋友，想用不赶时间的方式认识新的人。",
    description:
      "从武康路附近开始，走一段不超过两小时的路线，最后找家咖啡馆坐坐。没有破冰游戏，也不要求强行活跃。",
    tags: ["上海", "散步", "轻社交"],
    members: 4,
    minMembers: 4,
    maxMembers: 6,
    deadline: "2026.07.26",
    reason: "你希望关系从真实日常自然开始，这个局节奏轻，也给彼此留下充分观察空间。",
    observation: "成员都偏慢热，活动安排克制。当前还剩两席。",
    people: [
      { name: "阿简", summary: "编辑，常在周末逛旧书店。", offer: "路线与咖啡店清单" },
      { name: "牧川", summary: "交互设计师，喜欢城市观察。", offer: "轻松、不催促的相处节奏" },
    ],
  },
  {
    id: "opp-serious-relationship",
    scene: "love",
    type: "一对一认识",
    title: "认真认识，也允许慢一点",
    summary: "一位在杭州工作的建筑师，希望认识同样以长期关系为目标的人。",
    description:
      "更愿意从散步、看展或一起吃饭开始，不追求高频聊天。看重坦诚、稳定的生活节奏和对长期关系的共识。",
    tags: ["杭州", "长期关系", "慢节奏"],
    members: 1,
    minMembers: 2,
    maxMembers: 2,
    deadline: "2026.08.20",
    reason: "双方都把长期关系放在目标里，也都希望从低压力的线下见面开始。",
    observation: "目标和边界表达清楚，但仍需要确认城市与见面频率是否现实。",
    people: [
      { name: "知行", summary: "杭州，建筑师，工作日规律。", offer: "稳定投入和直接沟通" },
    ],
  },
  {
    id: "opp-weekend-makers",
    scene: "startup",
    type: "周末共创",
    title: "周末做点真正上线的小东西",
    summary: "设计、开发和运营混合小组，每月选一个真实问题做成可用工具。",
    description: "不做路演项目，也不承诺创业。每月两个周末，从问题选择到发布完成一个小而完整的作品。",
    tags: ["北京", "周末", "共创"],
    members: 5,
    minMembers: 4,
    maxMembers: 8,
    deadline: "2026.08.31",
    reason: "适合想保持主业、同时通过实际协作认识潜在伙伴的人。",
    observation: "参与方式灵活，但要求每月至少完整投入一个周末。",
    people: [
      { name: "闻舟", summary: "产品设计师，负责议题组织。", offer: "问题库和共创流程" },
      { name: "十一", summary: "前端工程师，喜欢快速原型。", offer: "工程实现和部署" },
    ],
  },
];
