import type { EventGuest } from "@/lib/types";

export const demoEventGuests: EventGuest[] = [
  {
    id: "demo-01",
    name: "陈序",
    tagline: "把 AI 能力做成真正有人用的产品",
    roles: ["算法", "工程"],
    company: "独立开发团队",
    stage: "有想法",
    position: "算法工程师",
    needs: ["找场景", "找数据", "找合伙人"],
    needDetail: "希望找到真实业务问题，先做一个可验证的小原型。",
    offers: ["技术能力", "原型开发"],
    offerDetail: "可以快速完成 AI 应用验证。",
  },
  {
    id: "demo-02",
    name: "唐宁",
    tagline: "长期在医疗一线寻找可落地的新工具",
    roles: ["医疗产品", "行业运营"],
    company: "明远医疗",
    stage: "跑通小闭环",
    position: "产品负责人",
    needs: ["找技术", "找产品伙伴"],
    needDetail: "需要能理解临床流程的技术伙伴共同验证。",
    offers: ["行业场景", "医院资源", "用户访谈"],
    offerDetail: "可以组织一线需求访谈和试点。",
  },
  {
    id: "demo-03",
    name: "周禾",
    tagline: "擅长让好产品被第一批用户看见",
    roles: ["内容", "增长"],
    company: "新岸工作室",
    stage: "商业模式扩张",
    position: "增长负责人",
    needs: ["找产品", "找客户"],
    needDetail: "希望参与一个有清楚用户价值的早期项目。",
    offers: ["内容流量", "增长策略", "品牌资源"],
    offerDetail: "可协助完成首轮内容与获客验证。",
  },
  {
    id: "demo-04",
    name: "苏哲",
    tagline: "关注产业与技术之间真正能形成闭环的项目",
    roles: ["投资", "战略"],
    company: "望岳资本",
    stage: "持续寻找项目",
    position: "投资经理",
    needs: ["找早期项目", "找行业场景"],
    needDetail: "关注医疗、企业服务和 AI 应用方向。",
    offers: ["资金", "商业建议", "产业人脉"],
    offerDetail: "可以提供早期融资与商业模型反馈。",
  },
  {
    id: "demo-05",
    name: "梁溪",
    tagline: "让临床问题更准确地进入产品研发",
    roles: ["临床研究", "成果转化"],
    company: "启明医学中心",
    stage: "跑通小闭环",
    position: "研究负责人",
    needs: ["找技术", "找成果转化伙伴"],
    needDetail: "希望围绕一个明确病种验证辅助决策工具。",
    offers: ["临床场景", "数据合作", "专家资源"],
    offerDetail: "可协助定义问题和设计试点。",
  },
  {
    id: "demo-06",
    name: "罗尧",
    tagline: "熟悉企业客户从兴趣到采购的完整路径",
    roles: ["销售", "渠道"],
    company: "北辰企业服务",
    stage: "商业模式扩张",
    position: "区域市场负责人",
    needs: ["找解决方案", "找技术产品"],
    needDetail: "需要能快速落地到企业客户的轻量方案。",
    offers: ["客户资源", "渠道资源", "销售能力"],
    offerDetail: "覆盖华北区域的企业客户与合作渠道。",
  },
  {
    id: "demo-07",
    name: "方琪",
    tagline: "把复杂流程变成用户愿意持续使用的体验",
    roles: ["产品", "设计"],
    company: "原点产品实验室",
    stage: "有想法",
    position: "产品设计师",
    needs: ["找技术", "找真实场景"],
    needDetail: "希望与工程伙伴完成一个端到端产品验证。",
    offers: ["产品能力", "交互设计", "用户研究"],
    offerDetail: "可以负责需求梳理、原型和测试。",
  },
  {
    id: "demo-08",
    name: "何川",
    tagline: "用小规模真实交易验证每个商业判断",
    roles: ["创业者", "商业化"],
    company: "逐浪科技",
    stage: "完成 0-1",
    position: "创始人",
    needs: ["找渠道", "找合伙人", "找资金"],
    needDetail: "准备把已验证的方案复制到更多城市。",
    offers: ["行业场景", "供应链", "商业化经验"],
    offerDetail: "可以提供真实订单和试合作名额。",
  },
];
